### ISSUE TITLE
Spawned processes leak resources after 'being killed'

### ISSUE THREAD

**Issue by muse254** [muse254/hermes#1]
When changes are detected and a new process is spawned, the previous process' resources have not been cleaned. In my case its the port number. Sth of a zombie process still lingers on  =(
Still looking into it. I'd like help or insight.

**Comment by itsyaasir** [comment]
Do you think a simple cleanup code of the previous project will Suffice.

**Comment by muse254** [comment]
In theory doing Kill() kills the process and Release() should release any
resources that were bound to it. The process is unusable afterwards and an
exit code for it can also be extracted. I assume it has been killed.
Probably that's where the bug comes in?!
In one case the process is killed yet on another it lives on as a 'zombie'
process until hermes exits. At least the in my case the tcp address for the
server.
'address already in use' error comes up.

**Comment by muse254** [comment]
Bingo.
go run internally does a go build -o prog and ./prog, so when you kill the go run process, you don't kill it's subprocess ./prog. 

I'll trying doing go build prog and ./prog for 'go run' and see how it goes

**Comment by muse254** [comment]
Works like a charm @Majorkid
